server:
  # If true, or "-" with global.enabled true, Vault server will be installed.
  # See vault.mode in _helpers.tpl for implementation details.
  enabled: "-"

  dataStorage:
    enabled: true
    # Size of the PVC created
    size: 10Gi
    # Location where the PVC will be mounted.
    mountPath: "/vault/data"
    # Name of the storage class to use.  If null it will use the, in this case I am Cephfs
    storageClass: cephfs-retain
    # Access Mode of the storage device being used for the PVC
    accessMode: ReadWriteOnce
    # Annotations to apply to the PVC
    annotations: {}
    # Labels to apply to the PVC
    labels: {}
 
  # Resource requests, limits, etc. for the server cluster placement. This
  # should map directly to the value of the resources field for a PodSpec.
  # By default no direct resource request is made.

  image:
    repository: "hashicorp/vault"
    tag: "1.13.3"
    pullPolicy: IfNotPresent

  # Watch out! this is what will unseal your Server.
  postStart: 
    - /bin/sh
    - -c 
    - echo starting post start ... && sh /opt/vault/scripts/unseal.sh

  volumes:
    - name: unseal
      secret:
        secretName: unseal-script

  volumeMounts:
    - name: unseal
      mountPath: /opt/vault/scripts/unseal.sh
      subPath: unseal.sh  
    